name: Check Format

on:
  push:
    branches:
      - master
      - main

jobs:
  run-unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: ${{ matrix.os }} python-${{ matrix.python-version }}
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install build-essential python3-dev libcairo2-dev libpango1.0-dev texlive-full
          pip install -r requirements.txt
          pip install flake8
      - name: Check Format with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. Black has 88 max-line-length
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

