name: Publish TestPyPI

on:
  push:
      branches:
      - master
      - main

jobs:
  publish-to-testpypi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    name: ${{ matrix.os }} python-${{ matrix.python-version }}
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install build twine
      - name: Update version for TestPyPI
        run: |
          VERSION_SUFFIX=$(date +%Y%m%d%H%M%S)
          sed -i "s/^version = \"\(.*\)\"/version = \"\1.dev$VERSION_SUFFIX\"/" pyproject.toml
      - name: Build distribution
        run: |
          python -m build
      - name: Publish to TestPyPI
        run: |
          python -m twine upload --verbose --repository testpypi dist/*
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}