
  
name: Run Unittests

on:
  push:
    branches:
      - master
      - main

jobs:
  run-unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: ${{ matrix.os }} python-${{ matrix.python-version }}
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          uv venv --python ${{ matrix.python-version }}
          echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          sudo apt install texlive-full
          uv pip install -r pyproject.toml
          uv pip install --group dev
      - name: Run Unittests
        run: |
          pytest

