name: Run Unittests

on:
  push:
    branches:
      - master
      - main

jobs:
  run-unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: ${{ matrix.os }} python-${{ matrix.python-version }}
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install build-essential python3-dev libcairo2-dev libpango1.0-dev texlive-full ffmpeg
          pip install -r requirements.txt
          pip install pytest
      - name: Run Unittests
        run: |
          pytest
